# Generated by Django 5.0.3 on 2024-03-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='title',
            new_name='name',
        ),
    ]
