# Generated by Django 5.0.3 on 2024-03-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post_remove_following_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POST',
            new_name='Posting',
        ),
    ]
