# Generated by Django 5.0.3 on 2024-03-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='no_of_likes',
        ),
    ]
