# Generated by Django 5.0.3 on 2024-03-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_likes_likes_likes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
