# Generated by Django 5.0.3 on 2024-03-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_posting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='user',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
