# Generated by Django 5.0.3 on 2024-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_posting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
