# Generated by Django 5.0.3 on 2024-04-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_newsfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='caption',
            field=models.CharField(max_length=150),
        ),
    ]
