# Generated by Django 5.0.3 on 2024-04-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_newsfeed_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='video',
            field=models.FileField(blank=True, upload_to='post_videos'),
        ),
    ]
